Add additional release-drafter tags
geeksforsocialchange/imok pull request #55
Opened 2021-05-08 15:14 UTC by kimadactyl

2021-05-08 15:27 UTC, ghost commented
You probably want to update `.github/workflows/issue-label-assign.yml` to map git commit messages to labels for this to use, but I like what this is aiming for

2021-05-09 11:46 UTC, kimadactyl commented
How's that?

2021-05-09 13:08 UTC, ghost requested changes
Lets keep the number of labels to a minimum and map multiple commit messages to a single label

2021-05-09 13:22 UTC, kimadactyl reviewed
LGTM

2021-05-09 13:23 UTC, merged